services:
  mongodb:
    image: mongo:7
    container_name: sk-makeup-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: change_me_admin
      MONGO_INITDB_DATABASE: sk_makeup_artist
    volumes:
      - sk_makeup_mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sk_makeup_mongo_data:
